lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do
    plug MangoWeb.Plugs.FetchCart
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.Locale
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/", PageController, :index

    get "/categories/:name", CategoryController, :show

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/cart", CartController, :show
    post "/cart", CartController, :add
    put "/cart", CartController, :update

  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateCustomer]

    get "/checkout", CheckoutController, :edit
    put "/checkout/confirm", CheckoutController, :update

    get "/orders", OrderController, :index
    get "/orders/:id", OrderController, :show

    get "/logout", SessionController, :delete

    resources "/tickets", TicketController,
      except: [:edit, :update, :delete]
  end

end

lib/mango/sales/order.ex
defmodule Mango.Sales.Order do
  use Ecto.Schema
  import Ecto.Changeset

  alias Mango.Sales.LineItem

  schema "orders" do
    field :status, :string
    field :total, :decimal
    field :comments, :string
    field :customer_id, :integer
    field :customer_name, :string
    field :email, :string
    field :residence_area, :string

    embeds_many :line_items, LineItem, on_replace: :delete

    timestamps()
  end

  @doc false
  def changeset(order, attrs) do
    order
    |> cast(attrs, [:status, :total])
    |> cast_embed(:line_items, required: true, with: &LineItem.changeset/2)
    |> set_order_total
    |> validate_required([:status, :total])
  end

  def checkout_changeset(order, attrs) do
    changeset(order, attrs)
    |> cast(attrs, [:customer_id, :customer_name, :residence_area, :email, :comments])
    |> validate_required([:customer_id, :customer_name, :residence_area, :email])
  end

  defp set_order_total(changeset) do
    items = get_field(changeset, :line_items)
    total = Enum.reduce(items, Decimal.new(0), fn(item, acc) ->
      Decimal.add(acc, item.total)
    end)
    changeset
    |> put_change(:total, total)
  end

end

lib/mango_web/controllers/order_controller.ex
defmodule MangoWeb.OrderController do
  use MangoWeb, :controller

  alias Mango.Sales

  def index(conn, _params) do
    customer = conn.assigns.current_customer
    orders = Sales.get_customer_orders(customer)

    render conn, "index.html", customer: customer, orders: orders
  end

  def show(conn, %{"id" => id}) do
    customer = conn.assigns.current_customer
    order = Sales.get_order(id)

    if customer.id == order.customer_id  do
      render conn, "show.html", order: order
    else
      conn
      |> put_status(:not_found)
      |> put_view(MangoWeb.ErrorView)
      |> render("404.html")
    end
  end

end

lib/mango_web/views/order_view.ex
defmodule MangoWeb.OrderView do
  use MangoWeb, :view

end

lib/mango_web/templates/order/index.html.eex
<h1 class="page-title"><%= @customer.name %>'s Orders</h1>

<table>
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Order Status</th>
            <th>Order Total</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <%= for order <- @orders do %>
            <tr class="order">
                <td><%= order.id %></td>
                <td class="order-status"><%= order.status %></td>
                <td class="order-total">£ <%= order.total %></td>
                <td class="order-details-link"><%= link "View Order Details", to: order_path(@conn, :show, order.id) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

lib/mango_web/templates/order/show.html.eex
<h1 class="order-id">Show me my order <%= @order.id %>!</h1>

<ul>
    <li class="order-status">Status: <%= @order.status %></li>
    <li class="order-total">Total: £ <%= @order.total %></li>
    <%= if @order.comments do %>
        <li class="order-comments">Comments: <%= @order.comments %></li>
    <% end %>

    <table class="table">
        <thead>
            <tr>
              <th>Product name</th>
              <th>Pack size</th>
              <th>Quantity</th>
              <th>Unit price</th>
              <th>Subtotal</th>
            </tr>
        </thead>
        <tbody class="order-line-items">
            <%= for line_item <- @order.line_items do %>
                <tr>
                    <td class="product-name"><%= line_item.product_name %></td>
                    <td class="pack-size"><%= line_item.pack_size %></td>
                    <td class="quantity"><%= line_item.quantity %></td>
                    <td class="unit-price">£ <%= line_item.unit_price %></td>
                    <td class="total">£ <%= line_item.total %></td>
                </tr>
            <% end %>

        </tbody>
    </table>
</ul>