lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do
    plug MangoWeb.Plugs.FetchCart
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.Locale
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/", PageController, :index

    get "/categories/:name", CategoryController, :show

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/cart", CartController, :show
    post "/cart", CartController, :add
    put "/cart", CartController, :update

  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateCustomer]

    get "/checkout", CheckoutController, :edit
    put "/checkout/confirm", CheckoutController, :update

    get "/orders", OrderController, :index
    get "/orders/:id", OrderController, :show

    get "/logout", SessionController, :delete

    resources "/tickets", TicketController,
      except: [:edit, :update, :delete]
  end

end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view

  import MangoWeb.CartView, only: [cart_count: 1]
  
  def cart_link_text(conn) do
    raw """
      <i class="fa fa-shopping-cart"></i> <span class="cart-count">#{cart_count(conn)}</span>
    """
  end

  def get_active_locale_class(locale) do
    if Gettext.get_locale(MangoWeb.Gettext) == locale, do: "active"
  end

end

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Mango!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "app_nav.html", conn: @conn, customer: @current_customer %>
    
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top"> 
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#primary-nav">
        <span class="sr-only">Toggle navigation</span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
      <img src="/images/logo.png"/> Mango </a>
    </div>
    <div class="collapse navbar-collapse" id="primary-nav">

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link cart_link_text(@conn), 
              to: cart_path(@conn, :show), 
              class: "cart nav-link" %>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-globe"></i><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li class="<%= get_active_locale_class("en") %>"><a href="?locale=en">English</a></li>
                <li class="<%= get_active_locale_class("fr") %>"><a href="?locale=fr">Français</a></li>
                <li class="<%= get_active_locale_class("es") %>"><a href="?locale=es">Espanol</a></li>
            </ul>
        </li>

        <%= if @customer do %>    
        <li class="dropdown">
          <a href="#" id="user-menu" class="dropdown-toggle" data-toggle="dropdown">
            <%= @customer.name %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link "My orders", to: "/orders", id: "orders-link" %></li>
            <li><%= link "Log out", to: "/logout" %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link "Register", to: registration_path(@conn, :new), class: "nav-link" %></li>
          <li><%= link "Sign in", to: session_path(@conn, :new), class: "nav-link" %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav"> 
        <li><%= link "Fruits", to: category_path(@conn, :show, "fruits") %></li>
        <li><%= link "Vegetables", to: category_path(@conn, :show, "vegetables") %></li>
      </ul> 
    </div>
  </div>
</nav>