lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do
    plug MangoWeb.Plugs.FetchCart
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.Locale
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/", PageController, :index

    get "/categories/:name", CategoryController, :show

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/cart", CartController, :show
    post "/cart", CartController, :add
    put "/cart", CartController, :update

  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateCustomer]

    get "/checkout", CheckoutController, :edit
    put "/checkout/confirm", CheckoutController, :update

    get "/orders", OrderController, :index
    get "/orders/:id", OrderController, :show

    get "/logout", SessionController, :delete

    resources "/tickets", TicketController,
      except: [:edit, :update, :delete]
  end

end

lib/mango_web/controllers/cart_controller.ex
defmodule MangoWeb.CartController do
  use MangoWeb, :controller

  alias Mango.Sales

  def add(conn, %{"cart" => cart_params}) do
    cart = conn.assigns.cart
    case Sales.add_to_cart(cart, cart_params) do
      {:ok, cart} ->
        render(conn, "add.json", cart: cart, cart_params: cart_params)
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:info, "Error adding product to cart")
        |> redirect(to: page_path(conn, :index))
    end
  end

  def show(conn, _params) do
    cart = conn.assigns.cart
    cart_changeset = Sales.change_cart(cart)

    render conn, "show.html", cart: cart, cart_changeset: cart_changeset
  end

  def update(conn, %{"order" => cart_params}) do
    cart = conn.assigns.cart

    case Sales.update_cart(cart, cart_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Cart updated successfully")
        |> redirect(to: cart_path(conn, :show))
      {:error, _} ->
        conn
        |> put_flash(:info, "Error updating cart")
        |> redirect(to: cart_path(conn, :show))
    end
  end

end

lib/mango_web/views/cart_view.ex
defmodule MangoWeb.CartView do
  use MangoWeb, :view

  alias Mango.Sales.Order

  def render("add.json", %{cart: cart, cart_params: cart_params}) do
    %{"product_name" => name, "pack_size" => size, "quantity" => qty} = cart_params

    %{message: "Product added to cart - #{name}(#{size}) x #{qty} qty", cart_count: cart_count(cart)}
  end

  def cart_count(conn = %Plug.Conn{}) do
    cart_count(conn.assigns.cart)
  end

  def cart_count(cart = %Order{}) do
    Enum.reduce(cart.line_items, 0, fn(item, accumulator) ->
      accumulator + item.quantity
    end)
  end

end

lib/mango_web/templates/cart/show.html.eex
<h1>Cart</h1>

<%= if Enum.empty? (@cart.line_items) do %>
  <p>Your cart is empty</p>
<% else %>
  <%= form_for @cart_changeset, "/cart", fn f -> %>
    <table class="table">
      <thead>
        <tr>
          <th>Product name</th>
          <th>Pack size</th>
          <th>Quantity</th>
          <th>Unit price</th>
          <th>Subtotal</th>
          <th>Remove?</th>
        </tr>
      </thead>

      <tbody>
        <%= inputs_for f, :line_items, fn lf -> %>
          <tr>
            <td><%= lf.data.product_name %></td>
            <td><%= lf.data.pack_size %></td>
            <td>
              <%= hidden_input lf, :product_id %>
              <%= number_input lf, :quantity %>
              <%= error_tag lf, :quantity %>
            </td>
            <td>£ <%= lf.data.unit_price %></td>
            <td>£ <%= lf.data.total %></td>
            <td><%= checkbox lf, :delete %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan=4>Order Total</td>
          <td>£ <%= @cart.total %></td>
        </tr>
      </tbody>

    </table>
    <div class="form-group">
      <%= submit "Update Cart", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link "Checkout", to: checkout_path(@conn, :edit), class: "btn btn-primary pull-right" %>

<% end %>